CREATE DATABASE IF NOT EXISTS arms;

--creating student table
CREATE TABLE IF NOT EXISTS student(SRN VARCHAR(15) PRIMARY KEY , Name VARCHAR(30) NOT NULL UNIQUE , Department  VARCHAR(10) NOT NULL UNIQUE , Semester INT NOT NULL UNIQUE , S_Password NOT NULL);

--creating resource table
CREATE TABLE IF NOT EXISTS resources(RID INT PRIMARY KEY , Title VARCHAR(30) NOT NULL UNIQUE , Descriptions VARCHAR(30) NOT NULL UNIQUE , resource_type VARCHAR(20) NOT NULL UNIQUE , view_count INT NOT NULL UNIQUE);

--creating professor table
CREATE TABLE IF NOT EXISTS professor (PID INT PRIMARY KEY,RID INT PRIMARY KEY , P_Name VARCHAR(30) NOT NULL UNIQUE , Department VARCHAR(10) NOT NULL, P_Password VARCHAR(20) NOT NULL UNIQUE, FOREIGN KEY (RID) REFERENCES resources(RID));


--creating course table
CREATE TABLE IF NOT EXISTS course(CID INT PRIMARY KEY , course_name VARCHAR(20) NOT NULL UNIQUE , Semester INT NOT NULL UNIQUE);

--creating saved_as table
CREATE TABLE IF NOT EXISTS saved_as(RID INT PRIMARY KEY , FOREIGN KEY (RID) REFERENCES resources(RID));

--creating bookmark
CREATE TABLE IF NOT EXISTS bookmark(RID INT NOT NULL UNIQUE , SRN VARCHAR(15) NOT NULL UNIQUE , FOREIGN KEY (RID) REFERENCES saved_as(RID) , FOREIGN KEY (SRN) REFERENCES student(SRN));

--creating teaches table
CREATE TABLE IF NOT EXISTS teaches(PID INT PRIMARY KEY , CID INT PRIMARY KEY , FOREIGN KEY (PID) REFERENCES professor(PID) , FOREIGN KEY (CID) REFERENCES course(CID));

--creating enrolled_in table
CREATE TABLE IF NOT EXISTS enrolled_in(SRN INT PRIMARY KEY , CID INT PRIMARY KEY , FOREIGN KEY (SRN) REFERENCES student(SRN) , FOREIGN KEY (CID) REFERENCES course(CID));

--creating accesses table
CREATE TABLE IF NOT EXISTS accesses(SRN VARCHAR(15) PRIMARY KEY , RID INT PRIMARY KEY ,  FOREIGN KEY (SRN) REFERENCES student(SRN) , FOREIGN KEY (RID) REFERENCES resources(RID));

--creating under table
CREATE TABLE IF NOT EXISTS under(RID INT PRIMARY KEY , FOREIGN KEY (RID) REFERENCES resources(RID));

--creating tag table
CREATE TABLE IF NOT EXISTS tag(tag_name VARCHAR(20) NOT NULL UNIQUE , RID INT NOT NULL UNIQUE , CID INT NOT NULL UNIQUE , FOREIGN KEY (RID) REFERENCES under(RID) , FOREIGN KEY (CID) REFERENCES course(CID));
